version: "3.8"

services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    # container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - db_network

  # Adminer để quản lý PostgreSQL, MySQL và MSSQL
  adminer:
    image: adminer:latest
    # container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - db_network

  # Chạy dự án Node/Express trong container
  app:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # Override DB host để app chạy trong Docker có thể kết nối tới container postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres_db
    depends_on:
      - postgres
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge

